# Copyright (c) 2024 Cloudflare, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause

port = 8788

[storage_proxy]
url = "http://localhost:4001"
# SECRET: This is a test secret. In production, we'll generate and securely provision the token.
auth_token = 'this-is-the-storage-proxy-auth-token'

[service]
env = "oxy"
role = "helper"
max_batch_duration = 360000
min_batch_interval_start = 259200
max_batch_interval_end = 259200
supported_hpke_kems = ["x25519_hkdf_sha256"]
default_version = "v09"
report_storage_epoch_duration = 300000
base_url = "http://127.0.0.1:8788"
allow_taskprov = true
default_num_agg_span_shards = 4

[service.taskprov]
vdaf_verify_key_init = "b029a72fa327931a5cb643dcadcaafa098fcbfac07d990cb9e7c9a8675fafb18" # SECRET
leader_auth = """{
  "bearer_token": "I-am-the-leader"
}""" # SECRET
collector_auth = """{
  "bearer_token": "I-am-the-collector"
}""" # SECRET
hpke_collector_config = """{
    "id": 44,
    "kem_id": "p256_hkdf_sha256",
    "kdf_id": "hkdf_sha256",
    "aead_id": "aes128_gcm",
    "public_key": "04bab04096f16c6ba1b7b645f70af8bf7995708fbfd916d352de6801924f7b725d7b66423b48164f9a84fcf37ee7d469e6097fa05eddc87f7b6fcfaf900f65d92e"
}
"""